# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import AI_explainability_pb2 as AI__explainability__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in AI_explainability_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShapExplainerServiceStub(object):
    """Service

    rpc stands for Remote Procedure Call - call a function on a remote server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Explain = channel.unary_unary(
                '/shap_explainer.ShapExplainerService/Explain',
                request_serializer=AI__explainability__pb2.ExplainRequest.SerializeToString,
                response_deserializer=AI__explainability__pb2.ExplainResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/shap_explainer.ShapExplainerService/HealthCheck',
                request_serializer=AI__explainability__pb2.HealthRequest.SerializeToString,
                response_deserializer=AI__explainability__pb2.HealthResponse.FromString,
                _registered_method=True)


class ShapExplainerServiceServicer(object):
    """Service

    rpc stands for Remote Procedure Call - call a function on a remote server
    """

    def Explain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShapExplainerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Explain': grpc.unary_unary_rpc_method_handler(
                    servicer.Explain,
                    request_deserializer=AI__explainability__pb2.ExplainRequest.FromString,
                    response_serializer=AI__explainability__pb2.ExplainResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=AI__explainability__pb2.HealthRequest.FromString,
                    response_serializer=AI__explainability__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shap_explainer.ShapExplainerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shap_explainer.ShapExplainerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShapExplainerService(object):
    """Service

    rpc stands for Remote Procedure Call - call a function on a remote server
    """

    @staticmethod
    def Explain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shap_explainer.ShapExplainerService/Explain',
            AI__explainability__pb2.ExplainRequest.SerializeToString,
            AI__explainability__pb2.ExplainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shap_explainer.ShapExplainerService/HealthCheck',
            AI__explainability__pb2.HealthRequest.SerializeToString,
            AI__explainability__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
