# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AI_explainability.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'AI_explainability.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x41I_explainability.proto\x12\x0eshap_explainer\"`\n\x0bOutputLabel\x12\r\n\x05index\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x0f\n\x07label_1\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x14\n\x0c\x65xtra_labels\x18\x05 \x03(\t\"\xd9\x02\n\x0e\x45xplainRequest\x12\x10\n\x08\x61nalysis\x18\x01 \x01(\t\x12\x0f\n\x07package\x18\x02 \x01(\t\x12\x12\n\nmodel_type\x18\x03 \x01(\t\x12\x12\n\nmodel_file\x18\x04 \x01(\x0c\x12\x14\n\x0c\x64\x61taset_file\x18\x05 \x01(\x0c\x12\x1c\n\x14\x62\x61\x63kground_data_file\x18\x06 \x01(\x0c\x12\x16\n\x0etest_data_file\x18\x07 \x01(\x0c\x12\x15\n\rfeature_names\x18\x08 \x03(\t\x12\x32\n\routput_labels\x18\t \x03(\x0b\x32\x1b.shap_explainer.OutputLabel\x12\x16\n\x0e\x65xplainer_type\x18\n \x01(\t\x12\x11\n\tinput_dim\x18\x0b \x01(\x05\x12\x13\n\x0bhidden_size\x18\x0c \x01(\x05\x12\x11\n\tlook_back\x18\r \x01(\x05\x12\x12\n\nlook_ahead\x18\x0e \x01(\x05\"\xa4\x01\n\x07ShapRow\x12\x14\n\x0ctarget_index\x18\x01 \x01(\x05\x12\x13\n\x0btarget_name\x18\x02 \x01(\t\x12\x14\n\x0csample_index\x18\x03 \x01(\x05\x12\x16\n\x0e\x66\x65\x61ture_values\x18\x04 \x03(\x02\x12\x12\n\nprediction\x18\x05 \x01(\x05\x12\x17\n\x0fprediction_cont\x18\x06 \x01(\x02\x12\x13\n\x0bshap_values\x18\x07 \x03(\x02\"\x8a\x01\n\x0f\x45xplainResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12*\n\tshap_rows\x18\x03 \x03(\x0b\x32\x17.shap_explainer.ShapRow\x12\x12\n\nexcel_file\x18\x04 \x01(\x0c\x12\x15\n\rnotebook_file\x18\x05 \x01(\x0c\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xb0\x01\n\x14ShapExplainerService\x12J\n\x07\x45xplain\x12\x1e.shap_explainer.ExplainRequest\x1a\x1f.shap_explainer.ExplainResponse\x12L\n\x0bHealthCheck\x12\x1d.shap_explainer.HealthRequest\x1a\x1e.shap_explainer.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AI_explainability_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OUTPUTLABEL']._serialized_start=43
  _globals['_OUTPUTLABEL']._serialized_end=139
  _globals['_EXPLAINREQUEST']._serialized_start=142
  _globals['_EXPLAINREQUEST']._serialized_end=487
  _globals['_SHAPROW']._serialized_start=490
  _globals['_SHAPROW']._serialized_end=654
  _globals['_EXPLAINRESPONSE']._serialized_start=657
  _globals['_EXPLAINRESPONSE']._serialized_end=795
  _globals['_HEALTHREQUEST']._serialized_start=797
  _globals['_HEALTHREQUEST']._serialized_end=812
  _globals['_HEALTHRESPONSE']._serialized_start=814
  _globals['_HEALTHRESPONSE']._serialized_end=846
  _globals['_SHAPEXPLAINERSERVICE']._serialized_start=849
  _globals['_SHAPEXPLAINERSERVICE']._serialized_end=1025
# @@protoc_insertion_point(module_scope)
